
(function(){
'use strict';
const DATA=window.DEUTSCHPATH_COURSE_DATA;
if(!DATA){console.error('Course data did not load.');return}
const app=window.__DeutschPath||{};const appState=app.state||{};
const STAGES=['discover','understand','practice','produce','retain','prove'];
const STAGE_LABELS={discover:'Discover',understand:'Understand',practice:'Practise',produce:'Produce',retain:'Retain',prove:'Prove'};
const WEIGHTS=DATA.masteryModel.weights;
function esc(value){return app.escapeHtml?app.escapeHtml(String(value??'')):String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function today(){return app.dateKey?app.dateKey():new Date().toISOString().slice(0,10)}
function persist(){try{if(app.saveState)app.saveState();else localStorage.setItem('deutschPathStateV29',JSON.stringify(appState));if(app.renderLevelTracker)app.renderLevelTracker()}catch(error){console.error(error)}}
function unique(items){return [...new Set(items)]}
function normalizeText(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[^a-z0-9äöü\s]/g,'').replace(/\s+/g,' ').trim()}
function visibleQuestionText(questions){return (questions||[]).flatMap(q=>[q.prompt,q.text,q.sentence,...(Array.isArray(q.options)?q.options:[]),...(Array.isArray(q.words)?q.words:[])]).filter(Boolean).join(' ')}
function ensureState(){
 if(!appState.courseEngine2||typeof appState.courseEngine2!=='object')appState.courseEngine2={version:2,units:{},checkpoints:{},lastUnitId:'ce001',authorDraft:null};
 const ce=appState.courseEngine2;if(!ce.units||typeof ce.units!=='object')ce.units={};if(!ce.checkpoints||typeof ce.checkpoints!=='object')ce.checkpoints={};if(!ce.lastUnitId)ce.lastUnitId='ce001';return ce;
}
const ceState=ensureState();
function unitRecord(id){if(!ceState.units[id])ceState.units[id]={stages:{},openedAt:null,lastOpenedAt:null};const r=ceState.units[id];if(!r.stages)r.stages={};return r}
function stageRecord(id,stage){const r=unitRecord(id);if(!r.stages[stage])r.stages[stage]={};return r.stages[stage]}
function stageComplete(id,stage){const r=stageRecord(id,stage);if(stage==='retain')return unique(r.dates||[]).length>=DATA.masteryModel.rules.minimumRetentionDays;if(stage==='produce')return !!r.completedAt&&String(r.writing||'').trim().length>=20&&r.spoken===true;if(stage==='practice'||stage==='prove'||stage==='understand')return Number(r.score||0)>= (stage==='understand'?67:80);return !!r.completedAt}
function unitProgress(id){let total=0;STAGES.forEach(s=>{if(stageComplete(id,s))total+=WEIGHTS[s]||0});return Math.min(100,total)}
function unitStatus(id){const p=unitProgress(id);if(stageComplete(id,'prove')&&stageComplete(id,'retain')&&p===100)return'Mastered';if(stageComplete(id,'retain'))return'Retained';if(stageComplete(id,'produce'))return'Recalled';if(stageComplete(id,'practice'))return'Practised';if(stageComplete(id,'discover'))return'Introduced';return'Not studied'}
function unitCourseComplete(id){return ['discover','understand','practice','produce','prove'].every(stage=>stageComplete(id,stage))}
function checkpointReadiness(cp){const ids=[];for(let n=cp.unitRange[0];n<=cp.unitRange[1];n++)ids.push(`ce${String(n).padStart(3,'0')}`);const authoredIds=ids.filter(id=>!!authoredUnit(id));const completedIds=authoredIds.filter(id=>unitCourseComplete(id));return{ids,authoredIds,completedIds,ready:cp.available&&authoredIds.length===ids.length&&completedIds.length===ids.length,missing:ids.filter(id=>!unitCourseComplete(id))}}
function prerequisiteReady(unit){if(!unit.prerequisites?.length)return true;return unit.prerequisites.every(id=>unitProgress(id)>=DATA.masteryModel.rules.unlockProgress)}
function unitAvailability(unit){if(!unit.authored)return'Outline';return prerequisiteReady(unit)?'Available':'Locked'}
function totalCourseProgress(){return Math.round(DATA.units.reduce((sum,u)=>sum+unitProgress(u.id),0)/DATA.units.length)}
function authoredUnit(id){return DATA.fullUnits.find(u=>u.id===id)}
function validation(){
 const errors=[],warnings=[];const ids=new Set();
 if(DATA.units.length!==130)errors.push(`Expected 130 mapped units; found ${DATA.units.length}.`);
 DATA.units.forEach((u,i)=>{if(ids.has(u.id))errors.push(`Duplicate unit ID ${u.id}.`);ids.add(u.id);if(u.number!==i+1)warnings.push(`Unit sequence mismatch near ${u.id}.`);(u.prerequisites||[]).forEach(p=>{if(!DATA.units.some(x=>x.id===p))errors.push(`${u.id} references missing prerequisite ${p}.`)})});
 DATA.fullUnits.forEach(u=>{const required=['discover','understand','practice','produce','retain','prove'];required.forEach(k=>{if(!u[k])errors.push(`${u.id} is missing ${k}.`)});if((u.objectives||[]).length<2)errors.push(`${u.id} needs at least two objectives.`);if((u.understand?.vocabulary||[]).length<5)warnings.push(`${u.id} has fewer than five vocabulary items.`);if((u.practice||[]).length<4)errors.push(`${u.id} needs at least four practice items.`);if((u.prove?.questions||[]).length<5)errors.push(`${u.id} needs at least five prove questions.`)});
 const authored=DATA.units.filter(u=>u.authored).length;if(authored!==DATA.fullUnits.length)errors.push('Authored flags and full unit records do not match.');
 const availableCp=DATA.checkpoints.filter(c=>c.available).length;if(availableCp<2)errors.push('The two pilot checkpoints are not operational.');
 warnings.push(`${DATA.units.filter(u=>!u.authored).length} mapped units are outlines awaiting full authoring.`);
 return{errors,warnings,valid:errors.length===0};
}
let currentUnitId=ceState.lastUnitId||'ce001';let currentStage='discover';let questionSession={};let checkpointSession=null;let authorDraft=null;
function updateTitleBindings(){try{titles.courseEngine='Course Engine';titles.checkpoints='Course checkpoints';titles.authoring='Authoring studio';pageRenderers.courseEngine=renderCourseMap;pageRenderers.checkpoints=renderCheckpoints;pageRenderers.authoring=renderAuthoring}catch(error){console.warn('Could not register Course Engine page renderers.',error)}}
function stageOptions(){const select=document.getElementById('ceStageFilter');if(!select||select.options.length>1)return;DATA.stageSummary.forEach(s=>select.insertAdjacentHTML('beforeend',`<option value="${esc(s.name)}">${esc(s.name)} (${s.units})</option>`))}
function renderValidationBanner(){const result=validation(),el=document.getElementById('ceValidationBanner');if(!el)return;el.innerHTML=result.valid?`<b>Course data validated.</b> ${DATA.units.length} mapped units, ${DATA.fullUnits.length} fully authored units and ${DATA.checkpoints.length} checkpoints. <span style="color:var(--muted)">${result.warnings.length} expected authoring warning(s).</span>`:`<b>Validation failed.</b> ${result.errors.length} error(s) require attention.`}
function renderCourseMap(){
 ensureState();stageOptions();document.getElementById('ceUnitCount').textContent=DATA.units.length;document.getElementById('ceAuthoredCount').textContent=DATA.fullUnits.length;document.getElementById('ceCheckpointCount').textContent=DATA.checkpoints.length;document.getElementById('ceCourseProgress').textContent=`${totalCourseProgress()}%`;renderValidationBanner();
 const summary=document.getElementById('ceStageSummary');summary.innerHTML=DATA.stageSummary.map(s=>`<span>${esc(s.name)} · ${s.units} units</span>`).join('');
 const search=normalizeText(document.getElementById('ceSearch')?.value);const stage=document.getElementById('ceStageFilter')?.value||'all';const statusFilter=document.getElementById('ceStatusFilter')?.value||'all';
 const units=DATA.units.filter(u=>{const availability=unitAvailability(u),status=unitStatus(u.id);const hay=normalizeText([u.title,u.description,(u.objectives||[]).join(' '),(u.tags||[]).join(' ')].join(' '));return(!search||hay.includes(search))&&(stage==='all'||u.stage===stage)&&(statusFilter==='all'||statusFilter===availability||statusFilter===status)});
 document.getElementById('ceCourseGrid').innerHTML=units.map(u=>{const p=unitProgress(u.id),status=unitStatus(u.id),availability=unitAvailability(u),locked=availability==='Locked';return`<article class="course-unit-card ${locked?'locked':''}" data-unit="${u.id}"><div class="course-unit-top"><div class="course-unit-number">${u.number}</div><div class="course-unit-title"><h4>${esc(u.title)}</h4><p>${esc(u.description)}</p></div><span class="status-pill ${status.toLowerCase().replace(' ','-')} ${locked?'locked':''}">${locked?'🔒 Locked':availability==='Outline'?'Outline':esc(status)}</span></div><div class="unit-meta"><span>${esc(u.level)}</span><span>${esc(u.stage)}</span><span>${u.estimatedMinutes} min</span><span>Checkpoint ${u.checkpoint}</span></div><ul class="unit-objectives">${(u.objectives||[]).slice(0,2).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="unit-actions"><div class="mini-progress"><span style="width:${p}%"></span></div><small>${p}%</small><button class="${u.authored?'primary':'secondary'} ce-open-unit" data-id="${u.id}">${u.authored?(locked?'Preview':'Open unit'):'View outline'}</button></div></article>`}).join('')||'<div class="empty-state">No units match these filters.</div>';
 document.querySelectorAll('.ce-open-unit').forEach(b=>b.onclick=()=>openUnit(b.dataset.id));
 document.getElementById('courseMapView').hidden=false;document.getElementById('ceUnitWorkspace').hidden=true;
}
function nextRecommendedUnit(){return DATA.units.find(u=>u.authored&&unitAvailability(u)==='Available'&&unitProgress(u.id)<100)||DATA.units.find(u=>u.authored)||DATA.units[0]}
function openUnit(id){const map=DATA.units.find(u=>u.id===id);if(!map)return;if(app.setActiveStudyContext)app.setActiveStudyContext(id,map.level,map.title,'course');currentUnitId=id;ceState.lastUnitId=id;const rec=unitRecord(id);rec.openedAt=rec.openedAt||new Date().toISOString();rec.lastOpenedAt=new Date().toISOString();persist();document.getElementById('courseMapView').hidden=true;document.getElementById('ceUnitWorkspace').hidden=false;currentStage=STAGES.find(s=>!stageComplete(id,s))||'discover';renderUnitWorkspace()}
function renderUnitWorkspace(){const map=DATA.units.find(u=>u.id===currentUnitId),unit=authoredUnit(currentUnitId);document.getElementById('ceUnitLevel').textContent=`${map.level} · Unit ${map.number}`;document.getElementById('ceUnitTitle').textContent=map.title;document.getElementById('ceUnitSubtitle').textContent=map.description;const status=unitStatus(map.id),p=unitProgress(map.id);const statusEl=document.getElementById('ceUnitStatus');statusEl.textContent=unitAvailability(map)==='Locked'?`🔒 Preview · ${status}`:status;statusEl.className=`status-pill ${status.toLowerCase()}`;document.getElementById('ceUnitProgressBar').style.width=`${p}%`;document.getElementById('ceUnitProgressText').textContent=`${p}% evidence-weighted progress`;document.getElementById('ceUnitObjectives').innerHTML=(map.objectives||[]).map(x=>`<div><span>✓</span><p>${esc(x)}</p></div>`).join('');
 const tabs=document.getElementById('ceUnitStageTabs');tabs.innerHTML=STAGES.map(s=>`<button class="unit-stage-tab ${currentStage===s?'active':''} ${stageComplete(map.id,s)?'complete':''}" data-stage="${s}" ${!unit?'disabled':''}>${stageComplete(map.id,s)?'✓ ':''}${STAGE_LABELS[s]}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{currentStage=b.dataset.stage;questionSession={};renderUnitWorkspace()});
 if(!unit){renderOutline(map);return}renderStage(unit,currentStage)
}
function renderOutline(map){const prereq=(map.prerequisites||[]).map(id=>DATA.units.find(u=>u.id===id)?.title||id);document.getElementById('ceStageContent').innerHTML=`<div class="course-note"><b>This unit is mapped but not yet fully authored.</b> The course engine stores its position, prerequisites, objectives and checkpoint relationship. Use the Authoring studio to build the complete content package.</div><div class="outline-list"><div class="outline-row"><b>Stage</b><span>${esc(map.stage)}</span></div><div class="outline-row"><b>Level</b><span>${esc(map.level)}</span></div><div class="outline-row"><b>Prerequisites</b><span>${prereq.length?prereq.map(esc).join(', '):'None'}</span></div><div class="outline-row"><b>Checkpoint</b><span>${map.checkpoint}</span></div><div class="outline-row"><b>Planned cycle</b><span>Discover → Understand → Practise → Produce → Retain → Prove</span></div></div><button class="primary" id="outlineAuthor">Open authoring studio</button>`;document.getElementById('outlineAuthor').onclick=()=>{document.getElementById('authorNumber').value=map.number;document.getElementById('authorLevel').value=map.level;document.getElementById('authorStage').value=map.stage;document.getElementById('authorTitle').value=map.title;document.getElementById('authorObjectives').value=(map.objectives||[]).join('\n');document.getElementById('authorPrerequisites').value=(map.prerequisites||[]).join(',');showPage('authoring')};}
function renderStage(unit,stage){const container=document.getElementById('ceStageContent'),map=DATA.units.find(x=>x.id===unit.id);if(app.setActiveStudyContext)app.setActiveStudyContext(unit.id,map?.level,map?.title,'course');if(stage==='discover')renderDiscover(unit,container);else if(stage==='understand')renderUnderstand(unit,container);else if(stage==='practice')renderQuestionSet(unit,'practice',unit.practice,container,80);else if(stage==='produce')renderProduce(unit,container);else if(stage==='retain')renderRetain(unit,container);else renderQuestionSet(unit,'prove',unit.prove.questions,container,unit.prove.passScore||80)}
function renderDiscover(unit,c){if(app.markVocabularyFromText)app.markVocabularyFromText([...(unit.discover.dialogue||[]).map(x=>x.text),visibleQuestionText(unit.discover.questions||[])].join(' '),'course',unit.id);c.innerHTML=`<div class="two-column"><div><span class="topic-tag">DISCOVER IN CONTEXT</span><h3>Read the dialogue</h3><div class="dialogue">${unit.discover.dialogue.map(l=>`<div class="dialogue-line"><b>${esc(l.speaker)}</b><span>${esc(l.text)}</span></div>`).join('')}</div><button class="secondary ce-speak" data-text="${esc(unit.discover.dialogue.map(x=>x.text).join(' '))}">🔊 Listen to dialogue</button></div><div><h3>Comprehension</h3><div id="ceDiscoverQuestions"></div><button class="primary" id="ceCheckDiscover">Check comprehension</button><div id="ceDiscoverResult"></div></div></div>`;renderQuestions('ceDiscoverQuestions',unit.discover.questions,'discover');document.getElementById('ceCheckDiscover').onclick=()=>gradeQuestions(unit,'discover',unit.discover.questions,67,'ceDiscoverResult');bindSpeak(c)}
function renderUnderstand(unit,c){const g=unit.understand.grammar;c.innerHTML=`<span class="topic-tag">UNDERSTAND THE PATTERN</span><h3>${esc(g.title)}</h3><div class="grammar-box"><p>${esc(g.explanation)}</p><div class="grammar-pattern">${esc(g.pattern)}</div><div>${g.examples.map(x=>`<p>✓ ${esc(x)}</p>`).join('')}</div><div class="common-mistakes">${g.commonMistakes.map(x=>`<div>⚠️ ${esc(x)}</div>`).join('')}</div></div><h3>Core vocabulary</h3><div class="course-vocab-grid">${unit.understand.vocabulary.map(w=>`<article class="course-vocab-card"><h4>${esc(w.word)} <button class="link-button ce-speak" data-text="${esc(w.word)}">🔊</button></h4><p>${esc(w.meaning)} · <small>${esc(w.plural)}</small></p><p><i>${esc(w.example)}</i></p><small>${esc(w.chunk)} · ${esc(w.memory)}</small></article>`).join('')}</div><h3 style="margin-top:18px">Quick check</h3><div id="ceUnderstandQuestions"></div><button class="primary" id="ceCheckUnderstand">Check understanding</button><div id="ceUnderstandResult"></div>`;if(app.markVocabularySeen)app.markVocabularySeen(unit.understand.vocabulary||[],'course',{context:unit.id});if(app.markVocabularyFromText)app.markVocabularyFromText([g.pattern,...(g.examples||[]),...(g.commonMistakes||[]),visibleQuestionText(unit.understand.quickCheck||[])].join(' '),'course',unit.id);renderQuestions('ceUnderstandQuestions',unit.understand.quickCheck,'understand');document.getElementById('ceCheckUnderstand').onclick=()=>gradeQuestions(unit,'understand',unit.understand.quickCheck,67,'ceUnderstandResult');bindSpeak(c)}
function renderQuestions(containerId,questions,key){questionSession[key]={answers:{},orders:{}};const el=document.getElementById(containerId);el.innerHTML=questions.map((q,i)=>questionHtml(q,i,key)).join('');el.querySelectorAll('[data-q-option]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.q),v=Number(b.dataset.value);questionSession[key].answers[i]=v;el.querySelectorAll(`[data-q-option][data-q="${i}"]`).forEach(x=>x.classList.toggle('selected',Number(x.dataset.value)===v))});el.querySelectorAll('[data-order-token]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.q),idx=Number(b.dataset.idx);const arr=questionSession[key].orders[i]||(questionSession[key].orders[i]=[]);if(arr.includes(idx))arr.splice(arr.indexOf(idx),1);else arr.push(idx);renderOrderAnswer(el,questions[i],i,key)});}
function questionHtml(q,i,key){if(q.type==='choice')return`<div class="engine-question"><b>${i+1}. ${esc(q.prompt)}</b><div class="engine-options">${q.options.map((o,j)=>`<button class="engine-option" data-q-option data-q="${i}" data-value="${j}">${esc(o)}</button>`).join('')}</div></div>`;if(q.type==='order')return`<div class="engine-question"><b>${i+1}. ${esc(q.prompt)}</b><div class="order-bank">${q.words.map((w,j)=>`<button class="order-token" data-order-token data-q="${i}" data-idx="${j}">${esc(w)}</button>`).join('')}</div><div class="order-answer" id="order-${key}-${i}"><small>Click words in order.</small></div></div>`;return`<div class="engine-question"><label><b>${i+1}. ${esc(q.prompt)}</b><input class="wide-input" data-q-input data-key="${key}" data-q="${i}" style="margin-top:9px"></label></div>`}
function renderOrderAnswer(root,q,i,key){const el=root.querySelector(`#order-${key}-${i}`);const arr=questionSession[key].orders[i]||[];el.innerHTML=arr.length?arr.map(idx=>`<span class="order-token">${esc(q.words[idx])}</span>`).join(''):'<small>Click words in order.</small>'}
function answerCorrect(q,i,key,root){if(q.type==='choice')return questionSession[key].answers[i]===q.answer;if(q.type==='order'){const arr=(questionSession[key].orders[i]||[]).map(idx=>q.words[idx]);return JSON.stringify(arr)===JSON.stringify(q.answer)}const value=root.querySelector(`[data-q-input][data-key="${key}"][data-q="${i}"]`)?.value||'';return(q.acceptable||[q.answer]).some(a=>normalizeText(a)===normalizeText(value))}
function correctAnswerText(q){if(q.type==='choice')return String((q.options||[])[q.answer]??'');if(q.type==='order')return Array.isArray(q.answer)?q.answer.join(' ').replace(/\s+([.,!?;:])/g,'$1'):String(q.answer||'');return String(q.answer||'')}
function concise(text,max=92){const value=String(text||'').replace(/\s+/g,' ').trim();if(value.length<=max)return value;return value.slice(0,max-1).replace(/\s+\S*$/,'')+'…'}
function hintLeaksAnswer(text,q){if(q.type!=='input')return false;const ans=normalizeText(correctAnswerText(q));return ans.length>2&&normalizeText(text).includes(ans)}
function basicHint(q,stage){const raw=String(q.hint||q.explanation||'Use the unit pattern and try again.');const authored=concise(stage==='prove'&&hintLeaksAnswer(raw,q)?'Use the words around the blank to identify the required form from this unit.':raw);if(stage==='practice')return authored;if(q.type==='order')return concise(`Word-order clue: ${authored}`,118);if(q.type==='choice')return concise(`Focus on the rule, not the translation: ${authored}`,118);if(q.type==='input'&&/translate/i.test(q.prompt||''))return 'Recall the exact expression from this unit; include the article if it was taught with one.';return concise(`Grammar/context clue: ${authored}`,118)}
function strongerHint(q,stage){const answer=correctAnswerText(q).trim(),safeExplanation=stage==='prove'&&hintLeaksAnswer(q.explanation||'',q)?'':String(q.explanation||'');if(q.type==='choice')return concise(`Compare verb position, case/article and endings. ${safeExplanation}`,145);if(q.type==='order'){const first=(Array.isArray(q.answer)?q.answer:[]).find(x=>!/^[.,!?;:]$/.test(String(x)))||'';return concise(`${safeExplanation||'Build the sentence from the main-clause pattern.'}${first?` Start with “${first}”.`:''}`,145)}if(!answer)return concise(safeExplanation||'Review the unit example.',145);const words=answer.split(/\s+/);if(words.length===1){const chars=Array.from(answer);return `The expected word starts with “${chars[0]}” and has ${chars.length} letters.${safeExplanation?` ${concise(safeExplanation,90)}`:''}`.trim()}return `The expected response has ${words.length} words.${safeExplanation?` ${concise(safeExplanation,105)}`:''}`.trim()}
function clearStageHints(root){root.querySelectorAll('.engine-question').forEach(box=>{box.classList.remove('missed');box.querySelector('.engine-hint')?.remove();box.querySelectorAll('.engine-option').forEach(btn=>btn.classList.remove('wrong','correct'))})}
function addStageHints(unit,stage,questions,root,wrongIndexes){clearStageHints(root);wrongIndexes.forEach(i=>{const q=questions[i],box=root.querySelectorAll('.engine-question')[i];if(!q||!box)return;box.classList.add('missed');if(q.type==='choice'){const selected=questionSession[stage]?.answers?.[i];if(Number.isInteger(selected))box.querySelector(`[data-q-option][data-q="${i}"][data-value="${selected}"]`)?.classList.add('wrong')}const hint=document.createElement('div');hint.className=`engine-hint ${stage==='practice'?'compact':''}`;const allowAnswer=stage!=='prove'&&stage!=='checkpoint';hint.innerHTML=`<span><b>💡</b> ${esc(basicHint(q,stage))}</span><div class="hint-actions"><button class="ghost hint-more" type="button" data-course-more-hint="${i}">More hint</button>${allowAnswer?`<button class="ghost hint-answer hidden" type="button" data-course-show-answer="${i}">Show answer</button>`:''}</div>`;box.appendChild(hint)});
root.querySelectorAll('[data-course-more-hint]').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.courseMoreHint),q=questions[i],hint=btn.closest('.engine-hint');if(!q||!hint)return;let more=hint.querySelector('.engine-more-hint');if(!more){more=document.createElement('div');more.className='engine-more-hint';more.textContent=strongerHint(q,stage);hint.appendChild(more)}hint.querySelector('.hint-answer')?.classList.remove('hidden');btn.disabled=true;btn.textContent='More hint shown'});
root.querySelectorAll('[data-course-show-answer]').forEach(btn=>btn.onclick=()=>{const i=Number(btn.dataset.courseShowAnswer),q=questions[i],hint=btn.closest('.engine-hint');if(!q||!hint)return;let reveal=hint.querySelector('.engine-answer-reveal');if(!reveal){reveal=document.createElement('div');reveal.className='engine-answer-reveal';reveal.textContent=`Answer: ${correctAnswerText(q)}`;hint.appendChild(reveal);if(q.type==='choice')root.querySelector(`[data-q-option][data-q="${i}"][data-value="${q.answer}"]`)?.classList.add('correct');if(app.markVocabularyFromText)app.markVocabularyFromText(correctAnswerText(q),'course',unit.id)}btn.disabled=true;btn.textContent='Answer shown'})}
function gradeQuestions(unit,stage,questions,pass,resultId){const root=document.getElementById(resultId).parentElement;let correct=0;const wrongIndexes=[];questions.forEach((q,i)=>{const ok=answerCorrect(q,i,stage,root);if(ok)correct++;else wrongIndexes.push(i)});const score=Math.round(correct/questions.length*100);const wasComplete=stageComplete(unit.id,stage);const rec=stageRecord(unit.id,stage);rec.score=Math.max(Number(rec.score||0),score);rec.lastAttemptAt=new Date().toISOString();rec.attempts=Number(rec.attempts||0)+1;if(score>=pass)rec.completedAt=rec.completedAt||new Date().toISOString();const nowComplete=stageComplete(unit.id,stage);if(nowComplete&&!wasComplete&&app.registerActivity)app.registerActivity('course',{id:`${unit.id}:${stage}`});else if(app.recordContribution)app.recordContribution(`course-${stage}`,1);persist();const el=document.getElementById(resultId);el.className=`stage-result ${score>=pass?'good':'bad'}`;if(wrongIndexes.length)addStageHints(unit,stage,questions,root,wrongIndexes);else clearStageHints(root);const hintText=wrongIndexes.length?(stage==='practice'?'Short hints are shown only under the questions you missed.':'Targeted hints are shown under the questions you missed. Use “More hint” only if you need it.'):'No missed questions.';el.innerHTML=`<b>${score}% · ${score>=pass?'Stage completed':'Try again'}</b><p>${hintText}</p>`;renderUnitHeaderOnly()}
function renderQuestionSet(unit,stage,questions,c,pass){if(app.markVocabularyFromText)app.markVocabularyFromText(visibleQuestionText(questions||[]),'course',unit.id);c.innerHTML=`<span class="topic-tag">${stage==='practice'?'CONTROLLED PRACTICE':'PROVE YOUR MASTERY'}</span><h3>${stage==='practice'?'Build accuracy before free production':'Unit challenge'}</h3><p>${stage==='practice'?`Score at least ${pass}% to complete this stage.`:`Try it independently first. If you miss a question, a targeted hint will appear without revealing the answer. Target: ${pass}%.`}</p><div id="ceSetQuestions"></div><button class="primary" id="ceGradeSet">Check answers</button><div id="ceSetResult"></div>`;renderQuestions('ceSetQuestions',questions,stage);document.getElementById('ceGradeSet').onclick=()=>gradeQuestions(unit,stage,questions,pass,'ceSetResult')}
function renderProduce(unit,c){const r=stageRecord(unit.id,'produce');if(app.markVocabularyFromText)app.markVocabularyFromText([unit.produce.writingPrompt,unit.produce.speakingPrompt].join(' '),'course',unit.id);c.innerHTML=`<span class="topic-tag">PRODUCE LANGUAGE</span><div class="produce-grid"><div class="produce-box"><h3>Writing task</h3><div class="course-note">${esc(unit.produce.writingPrompt)}</div><textarea id="ceProduceWriting" class="writing-input" placeholder="Write your German response…">${esc(r.writing||'')}</textarea><div class="objective-list">${unit.produce.writingChecklist.map(x=>`<div><span>✓</span><p>${esc(x)}</p></div>`).join('')}</div></div><div class="produce-box"><h3>Speaking task</h3><div class="course-note">${esc(unit.produce.speakingPrompt)}</div><p><b>Model after your attempt:</b></p><details><summary>Show model answer</summary><p>${esc(unit.produce.modelAnswer)}</p><button class="secondary ce-speak" data-text="${esc(unit.produce.modelAnswer)}">🔊 Listen</button></details><label style="display:flex;gap:9px;margin-top:18px"><input id="ceSpokenDone" type="checkbox" ${r.spoken?'checked':''}> I completed the speaking task aloud.</label></div></div><button class="primary" id="ceSaveProduce">Save production evidence</button><div id="ceProduceResult"></div>`;document.getElementById('ceSaveProduce').onclick=()=>{const wasComplete=stageComplete(unit.id,'produce');r.writing=document.getElementById('ceProduceWriting').value.trim();if(app.markVocabularyFromText)app.markVocabularyFromText(r.writing,'course',unit.id);r.spoken=document.getElementById('ceSpokenDone').checked;r.savedAt=new Date().toISOString();if(r.writing.length>=20&&r.spoken)r.completedAt=r.completedAt||new Date().toISOString();const nowComplete=stageComplete(unit.id,'produce');if(nowComplete&&!wasComplete&&app.registerActivity)app.registerActivity('course',{id:`${unit.id}:produce`});else if(app.recordContribution)app.recordContribution('course-produce',1);persist();const ok=stageComplete(unit.id,'produce'),el=document.getElementById('ceProduceResult');el.className=`stage-result ${ok?'good':'bad'}`;el.textContent=ok?'Production stage completed. Your writing and speaking evidence was saved.':'Write at least 20 characters and complete the speaking task.';renderUnitHeaderOnly()};const modelDetails=c.querySelector('details');if(modelDetails)modelDetails.addEventListener('toggle',()=>{if(modelDetails.open&&app.markVocabularyFromText)app.markVocabularyFromText(unit.produce.modelAnswer,'course',unit.id)});bindSpeak(c)}
function renderRetain(unit,c){const r=stageRecord(unit.id,'retain');if(app.markVocabularyFromText)app.markVocabularyFromText((unit.retain.reviewPrompts||[]).join(' '),'course',unit.id);const dates=unique(r.dates||[]);c.innerHTML=`<span class="topic-tag">RETAIN OVER TIME</span><h3>Delayed recall</h3><p>Mastery is not awarded immediately. Record successful review on at least ${unit.retain.minimumReviewDays||2} different days.</p><div class="course-note"><b>Review prompts</b>${unit.retain.reviewPrompts.map(x=>`<p>• ${esc(x)}</p>`).join('')}</div><div class="retention-days">${dates.length?dates.map(d=>`<span class="retention-day done">✓ ${esc(d)}</span>`).join(''):'<span class="retention-day">No delayed review recorded yet.</span>'}</div><button class="primary" id="ceRecordReview">Record successful review today</button><div id="ceRetainResult"></div>`;document.getElementById('ceRecordReview').onclick=()=>{const before=(r.dates||[]).includes(today());r.dates=unique([...(r.dates||[]),today()]);r.lastReviewAt=new Date().toISOString();if(!before&&app.registerActivity)app.registerActivity('course',{id:`${unit.id}:retain:${today()}`});else if(!before&&app.recordContribution)app.recordContribution('course-retain',1);persist();renderRetain(unit,c);renderUnitHeaderOnly()};}
function renderUnitHeaderOnly(){const map=DATA.units.find(u=>u.id===currentUnitId),status=unitStatus(map.id),p=unitProgress(map.id);document.getElementById('ceUnitProgressBar').style.width=`${p}%`;document.getElementById('ceUnitProgressText').textContent=`${p}% evidence-weighted progress`;document.getElementById('ceUnitStatus').textContent=status;document.getElementById('ceUnitStageTabs').querySelectorAll('button').forEach(b=>b.classList.toggle('complete',stageComplete(map.id,b.dataset.stage)))}
function bindSpeak(root){root.querySelectorAll('.ce-speak').forEach(b=>b.onclick=()=>{const text=b.dataset.text;if(app.speakText)app.speakText(text,0.85)})}
function renderCheckpoints(){const available=DATA.checkpoints.filter(c=>c.available).length,passed=Object.values(ceState.checkpoints).filter(x=>Number(x.bestScore||0)>=80).length;document.getElementById('cpSummary').textContent=`${passed} passed · ${available} operational`;document.getElementById('checkpointGrid').innerHTML=DATA.checkpoints.map(cp=>{const rec=ceState.checkpoints[cp.id]||{},r=checkpointReadiness(cp),canStart=cp.available&&r.ready,completed=r.completedIds.length,total=r.ids.length;const status=!cp.available?'Mapped':canStart?'Ready':`🔒 ${completed}/${total} units complete`;const note=!cp.available?'This checkpoint is waiting for authored course units.':canStart?'All prerequisite course units are complete.':`Complete Units ${cp.unitRange[0]}–${cp.unitRange[1]} first. A unit counts when Discover, Understand, Practise, Produce and Prove are completed.`;return`<article class="checkpoint-card ${canStart?'':'unavailable'}"><div class="panel-header"><div><span class="topic-tag">UNITS ${cp.unitRange[0]}–${cp.unitRange[1]}</span><h4>${esc(cp.title)}</h4></div><span class="status-pill">${esc(status)}</span></div><p>${esc(cp.description)}</p><div class="unit-meta">${cp.skills.map(x=>`<span>${esc(x)}</span>`).join('')}</div><p class="checkpoint-requirement">${esc(note)}</p><p><b>Best score:</b> ${Number(rec.bestScore||0)}%</p><button class="${canStart?'primary':'secondary'} cp-start" data-id="${cp.id}" ${canStart?'':'disabled'}>${canStart?'Start checkpoint':cp.available?'Complete course units first':'Awaiting authored units'}</button></article>`}).join('');document.querySelectorAll('.cp-start').forEach(b=>b.onclick=()=>startCheckpoint(b.dataset.id));document.getElementById('checkpointRunner').hidden=true}
function startCheckpoint(id){const cp=DATA.checkpoints.find(c=>c.id===id);if(!cp||!checkpointReadiness(cp).ready)return;if(app.markVocabularyFromText)app.markVocabularyFromText(visibleQuestionText(cp.questions||[]),'course');checkpointSession={cp,answers:{},orders:{}};const runner=document.getElementById('checkpointRunner');runner.hidden=false;runner.innerHTML=`<div class="panel-header"><div><span class="topic-tag">CHECKPOINT ${cp.number}</span><h3>${esc(cp.title)}</h3></div><button class="secondary" id="cpClose">Close</button></div><p class="course-note">This checkpoint is unlocked because all course units in this block are complete.</p><div id="cpQuestions"></div><button class="primary" id="cpGrade">Submit checkpoint</button><div id="cpResult"></div>`;questionSession.checkpoint={answers:{},orders:{}};renderQuestions('cpQuestions',cp.questions,'checkpoint');document.getElementById('cpClose').onclick=()=>runner.hidden=true;document.getElementById('cpGrade').onclick=()=>{let correct=0;cp.questions.forEach((q,i)=>{if(answerCorrect(q,i,'checkpoint',runner))correct++});const score=Math.round(correct/cp.questions.length*100);const rec=ceState.checkpoints[cp.id]||(ceState.checkpoints[cp.id]={attempts:0,bestScore:0});rec.attempts++;rec.bestScore=Math.max(rec.bestScore,score);rec.lastAttemptAt=new Date().toISOString();if(app.recordContribution)app.recordContribution('checkpoint',4);persist();const el=document.getElementById('cpResult');el.className=`stage-result ${score>=cp.passScore?'good':'bad'}`;el.innerHTML=`<div class="checkpoint-score">${score}%</div><b>${score>=cp.passScore?'Checkpoint passed':'Review the units and try again'}</b>`;renderCheckpoints();runner.hidden=false;runner.scrollIntoView({behavior:'smooth'})};runner.scrollIntoView({behavior:'smooth'})}
function draftFromForm(){let vocab=[],practice=[];const errors=[];try{vocab=JSON.parse(document.getElementById('authorVocab').value||'[]')}catch(e){errors.push('Vocabulary must be valid JSON.')}try{practice=JSON.parse(document.getElementById('authorPractice').value||'[]')}catch(e){errors.push('Practice questions must be valid JSON.')}const n=Number(document.getElementById('authorNumber').value||0);const draft={id:`ce${String(n).padStart(3,'0')}`,number:n,stage:document.getElementById('authorStage').value.trim(),level:document.getElementById('authorLevel').value,title:document.getElementById('authorTitle').value.trim(),subtitle:'',estimatedMinutes:45,prerequisites:document.getElementById('authorPrerequisites').value.split(',').map(x=>x.trim()).filter(Boolean),objectives:document.getElementById('authorObjectives').value.split('\n').map(x=>x.trim()).filter(Boolean),tags:[],discover:{dialogue:document.getElementById('authorDialogue').value.split('\n').map(line=>{const idx=line.indexOf(':');return idx>0?{speaker:line.slice(0,idx).trim(),text:line.slice(idx+1).trim()}:null}).filter(Boolean),questions:[]},understand:{grammar:{title:document.getElementById('authorGrammarTitle').value.trim(),explanation:document.getElementById('authorGrammarExplanation').value.trim(),pattern:'',examples:[],commonMistakes:[]},vocabulary:Array.isArray(vocab)?vocab:[],quickCheck:[]},practice:Array.isArray(practice)?practice:[],produce:{writingPrompt:'',writingChecklist:[],speakingPrompt:'',modelAnswer:''},retain:{reviewPrompts:[],minimumReviewDays:2},prove:{questions:[],passScore:80}};return{draft,parseErrors:errors}}
function validateDraft(draft,parseErrors=[]){const errors=[...parseErrors],warnings=[];if(!draft.number||draft.number<1)errors.push('Unit number is required.');if(!draft.title)errors.push('Title is required.');if(draft.objectives.length<2)errors.push('Add at least two learning objectives.');if(draft.discover.dialogue.length<2)errors.push('Add at least two dialogue lines.');if(!draft.understand.grammar.title||!draft.understand.grammar.explanation)errors.push('Grammar title and explanation are required.');if(draft.understand.vocabulary.length<5)warnings.push('Recommended: at least five vocabulary items.');if(draft.practice.length<4)warnings.push('Recommended: at least four practice questions.');if(DATA.units.some(u=>u.id===draft.id))warnings.push(`${draft.id} already exists in the curriculum map.`);warnings.push('Produce, retain and prove details should be completed before publishing.');return{errors,warnings,valid:errors.length===0}}
function renderAuthoring(){const result=validation();document.getElementById('courseValidationDetails').innerHTML=[...result.errors.map(x=>`<div class="validation-item"><span>❌ ${esc(x)}</span><b>Error</b></div>`),...result.warnings.map(x=>`<div class="validation-item"><span>⚠️ ${esc(x)}</span><b>Expected</b></div>`)].join('')||'<div class="feedback good">No validation messages.</div>';if(authorDraft){document.getElementById('authorPreview').textContent=JSON.stringify(authorDraft,null,2)}}
function buildAuthorDraft(){const {draft,parseErrors}=draftFromForm();const result=validateDraft(draft,parseErrors);authorDraft=draft;ceState.authorDraft=draft;persist();document.getElementById('authorPreview').textContent=JSON.stringify(draft,null,2);document.getElementById('authorValidationStatus').textContent=result.valid?'Draft valid':'Draft needs work';document.getElementById('authorValidation').innerHTML=[...result.errors.map(x=>`<div class="validation-item"><span>❌ ${esc(x)}</span><b>Error</b></div>`),...result.warnings.map(x=>`<div class="validation-item"><span>⚠️ ${esc(x)}</span><b>Warning</b></div>`)].join('')||'<div class="feedback good">Draft passes validation.</div>';document.getElementById('authorDownload').disabled=!result.valid}
function clearAuthor(){['authorTitle','authorObjectives','authorPrerequisites','authorDialogue','authorGrammarTitle','authorGrammarExplanation','authorVocab','authorPractice'].forEach(id=>document.getElementById(id).value='');authorDraft=null;document.getElementById('authorPreview').textContent='Fill the form and build a draft.';document.getElementById('authorValidation').innerHTML='';document.getElementById('authorValidationStatus').textContent='No draft yet';document.getElementById('authorDownload').disabled=true}
function downloadDraft(){if(!authorDraft)return;const blob=new Blob([JSON.stringify(authorDraft,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${authorDraft.id}-${authorDraft.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')||'unit'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function attachListeners(){document.getElementById('ceSearch')?.addEventListener('input',renderCourseMap);document.getElementById('ceStageFilter')?.addEventListener('change',renderCourseMap);document.getElementById('ceStatusFilter')?.addEventListener('change',renderCourseMap);document.getElementById('ceContinue')?.addEventListener('click',()=>openUnit(nextRecommendedUnit().id));document.getElementById('ceValidateCourse')?.addEventListener('click',()=>{renderValidationBanner();showPage('authoring')});document.getElementById('ceBackToMap')?.addEventListener('click',renderCourseMap);document.getElementById('authorBuild')?.addEventListener('click',buildAuthorDraft);document.getElementById('authorClear')?.addEventListener('click',clearAuthor);document.getElementById('authorDownload')?.addEventListener('click',downloadDraft)}
function init(){updateTitleBindings();attachListeners();renderCourseMap();renderCheckpoints();renderAuthoring();window.__DeutschPathCourseEngine={DATA,validation,unitProgress,unitStatus,stageComplete,unitCourseComplete,checkpointReadiness,prerequisiteReady,openUnit,renderCourseMap,renderCheckpoints,buildAuthorDraft,ceState};if(location.hash==='#courseEngine')showPage('courseEngine');}
try{init();if(app.renderLevelTracker)app.renderLevelTracker()}catch(error){console.error('Course Engine 3.9 failed to initialize.',error);const el=document.getElementById('ceValidationBanner');if(el)el.textContent='Course Engine could not initialize. The rest of DeutschPath remains available.'}
})();
